telegram:
  api-url: https://api.telegram.org/
  webhook-path: ${telegram-web-hook-path} # https://api.telegram.org/bot5128213958:AAERMqZfvd5YsTwGRUAnYqsCBHu_2iMR6DM/setWebhook?url=https://4727-46-138-30-102.eu.ngrok.io

