server:
  port: 8080
#  servlet:
#    context-path: /lconobot

spring:

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false

#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=lconbot}
#    username: postgres
#    password: pgadmin
#
#  jpa:
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        ddl-auto: update

telegram:
  api-url: https://api.telegram.org/
  webhook-path: https://304f-46-138-30-102.eu.ngrok.io #https://4c17-46-138-30-102.eu.ngrok.io # https://api.telegram.org/bot5524243468:AAFIz6b8Vt5AQyBY5_P6ISECADvpvRlliu4/setWebhook?url=https://b3ad-46-138-30-102.eu.ngrok.io

yandex:
  api-weather-url: https://api.weather.yandex.ru/v2/informers

dadata:
  geocod-url: https://cleaner.dadata.ru/api/v1/clean/address
